// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: app/user/cmd/rpc/user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRegisterReq) Reset() {
	*x = UserRegisterReq{}
	mi := &file_app_user_cmd_rpc_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegisterReq) ProtoMessage() {}

func (x *UserRegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_cmd_rpc_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegisterReq.ProtoReflect.Descriptor instead.
func (*UserRegisterReq) Descriptor() ([]byte, []int) {
	return file_app_user_cmd_rpc_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserRegisterReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserRegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserRegisterRes struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Accesstonken      string                 `protobuf:"bytes,1,opt,name=Accesstonken,proto3" json:"Accesstonken,omitempty"`
	Expire            int64                  `protobuf:"varint,2,opt,name=Expire,proto3" json:"Expire,omitempty"`
	RefreshtokenAfter int64                  `protobuf:"varint,3,opt,name=RefreshtokenAfter,proto3" json:"RefreshtokenAfter,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserRegisterRes) Reset() {
	*x = UserRegisterRes{}
	mi := &file_app_user_cmd_rpc_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegisterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegisterRes) ProtoMessage() {}

func (x *UserRegisterRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_cmd_rpc_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegisterRes.ProtoReflect.Descriptor instead.
func (*UserRegisterRes) Descriptor() ([]byte, []int) {
	return file_app_user_cmd_rpc_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserRegisterRes) GetAccesstonken() string {
	if x != nil {
		return x.Accesstonken
	}
	return ""
}

func (x *UserRegisterRes) GetExpire() int64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

func (x *UserRegisterRes) GetRefreshtokenAfter() int64 {
	if x != nil {
		return x.RefreshtokenAfter
	}
	return 0
}

type UserLoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginReq) Reset() {
	*x = UserLoginReq{}
	mi := &file_app_user_cmd_rpc_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginReq) ProtoMessage() {}

func (x *UserLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_cmd_rpc_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginReq.ProtoReflect.Descriptor instead.
func (*UserLoginReq) Descriptor() ([]byte, []int) {
	return file_app_user_cmd_rpc_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserLoginReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserLoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserLoginRes struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Accesstonken      string                 `protobuf:"bytes,1,opt,name=Accesstonken,proto3" json:"Accesstonken,omitempty"`
	Expire            int64                  `protobuf:"varint,2,opt,name=Expire,proto3" json:"Expire,omitempty"`
	RefreshtokenAfter int64                  `protobuf:"varint,3,opt,name=RefreshtokenAfter,proto3" json:"RefreshtokenAfter,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserLoginRes) Reset() {
	*x = UserLoginRes{}
	mi := &file_app_user_cmd_rpc_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginRes) ProtoMessage() {}

func (x *UserLoginRes) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_cmd_rpc_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginRes.ProtoReflect.Descriptor instead.
func (*UserLoginRes) Descriptor() ([]byte, []int) {
	return file_app_user_cmd_rpc_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserLoginRes) GetAccesstonken() string {
	if x != nil {
		return x.Accesstonken
	}
	return ""
}

func (x *UserLoginRes) GetExpire() int64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

func (x *UserLoginRes) GetRefreshtokenAfter() int64 {
	if x != nil {
		return x.RefreshtokenAfter
	}
	return 0
}

var File_app_user_cmd_rpc_user_proto protoreflect.FileDescriptor

const file_app_user_cmd_rpc_user_proto_rawDesc = "" +
	"\n" +
	"\x1bapp/user/cmd/rpc/user.proto\x12\x02pb\"C\n" +
	"\x0fUserRegisterReq\x12\x14\n" +
	"\x05Phone\x18\x01 \x01(\tR\x05Phone\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\"{\n" +
	"\x0fUserRegisterRes\x12\"\n" +
	"\fAccesstonken\x18\x01 \x01(\tR\fAccesstonken\x12\x16\n" +
	"\x06Expire\x18\x02 \x01(\x03R\x06Expire\x12,\n" +
	"\x11RefreshtokenAfter\x18\x03 \x01(\x03R\x11RefreshtokenAfter\"@\n" +
	"\fUserLoginReq\x12\x14\n" +
	"\x05Phone\x18\x01 \x01(\tR\x05Phone\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\"x\n" +
	"\fUserLoginRes\x12\"\n" +
	"\fAccesstonken\x18\x01 \x01(\tR\fAccesstonken\x12\x16\n" +
	"\x06Expire\x18\x02 \x01(\x03R\x06Expire\x12,\n" +
	"\x11RefreshtokenAfter\x18\x03 \x01(\x03R\x11RefreshtokenAfter2i\n" +
	"\x04User\x124\n" +
	"\bRegister\x12\x13.pb.UserRegisterReq\x1a\x13.pb.UserRegisterRes\x12+\n" +
	"\x05Login\x12\x10.pb.UserLoginReq\x1a\x10.pb.UserLoginResB\x06Z\x04./pbb\x06proto3"

var (
	file_app_user_cmd_rpc_user_proto_rawDescOnce sync.Once
	file_app_user_cmd_rpc_user_proto_rawDescData []byte
)

func file_app_user_cmd_rpc_user_proto_rawDescGZIP() []byte {
	file_app_user_cmd_rpc_user_proto_rawDescOnce.Do(func() {
		file_app_user_cmd_rpc_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_user_cmd_rpc_user_proto_rawDesc), len(file_app_user_cmd_rpc_user_proto_rawDesc)))
	})
	return file_app_user_cmd_rpc_user_proto_rawDescData
}

var file_app_user_cmd_rpc_user_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_app_user_cmd_rpc_user_proto_goTypes = []any{
	(*UserRegisterReq)(nil), // 0: pb.UserRegisterReq
	(*UserRegisterRes)(nil), // 1: pb.UserRegisterRes
	(*UserLoginReq)(nil),    // 2: pb.UserLoginReq
	(*UserLoginRes)(nil),    // 3: pb.UserLoginRes
}
var file_app_user_cmd_rpc_user_proto_depIdxs = []int32{
	0, // 0: pb.User.Register:input_type -> pb.UserRegisterReq
	2, // 1: pb.User.Login:input_type -> pb.UserLoginReq
	1, // 2: pb.User.Register:output_type -> pb.UserRegisterRes
	3, // 3: pb.User.Login:output_type -> pb.UserLoginRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_user_cmd_rpc_user_proto_init() }
func file_app_user_cmd_rpc_user_proto_init() {
	if File_app_user_cmd_rpc_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_user_cmd_rpc_user_proto_rawDesc), len(file_app_user_cmd_rpc_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_user_cmd_rpc_user_proto_goTypes,
		DependencyIndexes: file_app_user_cmd_rpc_user_proto_depIdxs,
		MessageInfos:      file_app_user_cmd_rpc_user_proto_msgTypes,
	}.Build()
	File_app_user_cmd_rpc_user_proto = out.File
	file_app_user_cmd_rpc_user_proto_goTypes = nil
	file_app_user_cmd_rpc_user_proto_depIdxs = nil
}
