// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: user.proto

package server

import (
	"context"

	"github.com/csd-admin664/go_zero_study/app/user/cmd/rpc/internal/logic"
	"github.com/csd-admin664/go_zero_study/app/user/cmd/rpc/internal/svc"
	"github.com/csd-admin664/go_zero_study/app/user/cmd/rpc/pb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Register(ctx context.Context, in *pb.UserRegisterReq) (*pb.UserRegisterRes, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) Login(ctx context.Context, in *pb.UserLoginReq) (*pb.UserLoginRes, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
