// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: product.proto

package server

import (
	"context"

	"github.com/csd-admin664/go_zero_study/apps/product/rpc/internal/logic"
	"github.com/csd-admin664/go_zero_study/apps/product/rpc/internal/svc"
	"github.com/csd-admin664/go_zero_study/apps/product/rpc/product"
)

type ProductServer struct {
	svcCtx *svc.ServiceContext
	product.UnimplementedProductServer
}

func NewProductServer(svcCtx *svc.ServiceContext) *ProductServer {
	return &ProductServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductServer) Products(ctx context.Context, in *product.ProductRequest) (*product.ProductResponse, error) {
	l := logic.NewProductsLogic(ctx, s.svcCtx)
	return l.Products(in)
}

func (s *ProductServer) ProductInfo(ctx context.Context, in *product.ProductInfoRequest) (*product.ProductItem, error) {
	l := logic.NewProductInfoLogic(ctx, s.svcCtx)
	return l.ProductInfo(in)
}
