// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type UserLoginReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type UserLoginRes struct {
	Accesstonken      string `json:"accesstonken"`
	Expire            int64  `json:"expire"`
	RefreshtokenAfter int64  `json:"refreshtokenAfter"`
}

type UserRegisterReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type UserRegisterRes struct {
	Accesstonken      string `json:"accesstonken"`
	Expire            int64  `json:"expire"`
	RefreshtokenAfter int64  `json:"refreshtokenAfter"`
}
